name: CI

on:
  push:
    branches:
      - master
  pull_request_target:
  schedule:
    # Weekly Monday 5AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 5 * * 1'

jobs:
  cancel_ci:
    name: Mandatory checks before CI
    runs-on: ubuntu-latest
    steps:
    # Base branch check should run whether we skip CI or not
    - name: Check base branch
      uses: pllim/action-check_pr_basebranch@main
      with:
        BASEBRANCH_NAME: master
    - name: Failure means CI is skipped on purpose
      uses: pllim/action-skip-ci@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # This should only run if we did not skip CI
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@ce17749
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}

  # The rest only run if above are done

  pep_and_audit:
    name: PEP and audit
    runs-on: ubuntu-16.04
    needs: cancel_ci
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip flake8
        flake8 reftools --count
    # Make sure that packaging will work
    - name: pep517 build
      run: |
        python -m pip install --upgrade setuptools build "twine>=3.3"
        python -m build --sdist .
        twine check --strict dist/*
    - name: Security audit
      run: |
        python -m pip install --upgrade bandit
        bandit -r . -c .bandit.yaml

  initial_tests:
    name: Initial CI stage
    runs-on: ubuntu-latest
    needs: cancel_ci
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install and build
      run: |
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip setuptools
        python -m pip install -e .[test]
    - name: Test without optional deps
      run: pytest

  dev_deps_tests:
    name: CI with dev dependencies
    runs-on: ubuntu-latest
    needs: [pep_and_audit, initial_tests]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and build
      run: |
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip setuptools
        python -m pip install git+https://github.com/astropy/astropy.git@master#egg=astropy
        python -m pip install -e .[test]
    - name: Test with dev deps
      run: pytest

  old_deps_tests:
    name: CI with old dependencies
    runs-on: ubuntu-16.04
    needs: [pep_and_audit, initial_tests]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install and build
      run: |
        sudo apt-get install libxml2-utils
        python -m pip install --upgrade pip setuptools
        python -m pip install numpy==1.16.6
        python -m pip install astropy==3.2.2
        python -m pip install -e .[test]
    - name: Test with old deps
      run: pytest

  other_oses:
    name: CI in Win and OSX
    runs-on: ${{ matrix.os }}
    needs: [pep_and_audit, initial_tests]
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -e .[test]
    - name: Run tests
      run: pytest

  link_check:
    name: Link check
    runs-on: ubuntu-latest
    needs: [pep_and_audit, initial_tests]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools sphinx-astropy
        python -m pip install -e .
    - name: Docs link check
      run: |
        cd docs
        make linkcheck
      shell: bash
